name: Tests

on: [ push ]

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest  (no redis yet)
        node-version:
          - 10
          - 12
          - 14
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm install
    - run: npm test
      env:
        CI: true
